### ISSUE TITLE
#Question: Has this been tested on CCTV VNC Sessions?

### ISSUE THREAD

**Issue by NovaCygni** [0x3a/stargate#1]
As question, im curious as to if this has been tested on business CCTV Setups that use a VNC session for managers to remotely view/control the CCTV Panel?
Awesome work btw guys :+1: 
NovaCygni

Ps: I have 2 at my work, if you guys want I can give feedback on success/issues I encounter.

**Comment by 0x3a** [comment]
Keep in mind this is a vulnerability in a specific VNC software implementation known as VNC repeaters, these allow proxying of VNC sessions (but in fact a lot more besides VNC which is the vulnerability). If your CCTV setup just runs VNC your attack vector is simply the VNC (assuming you do have authentication on it) and not this tunneling vector.

To conclude: normal VNC implementations do not have any tunneling like VNC repeaters enabled so you don't have to worry about standard VNC implementation setups (unless you put them on the internet without authentication ;) )

Does this answer your question?

**Comment by NovaCygni** [comment]
Yep. Thanks alot :)
